Fix/nav bar
jsankare/CMS-semestriel-1 pull request #28
Opened 2024-06-04 19:15 UTC by pierre265

2024-06-06 08:03 UTC, jsankare requested changes
Tu n'as pas pris en compte le commentaire que j'avais fait sur le fait qu'il y ai toujours le bouton de deco sur la page de register et de login

2024-06-06 08:17 UTC, pierre265 commented
> Tu n'as pas pris en compte le commentaire que j'avais fait sur le fait qu'il y a toujours le bouton de déco sur la page de inscription et de connexion

Oui je n'ai pas encore fix cette remarque

2024-06-06 08:26 UTC, pierre265 commented
Chez moi tout fonctionne bien, sauf bouton de déco sur la page de inscription et de connexion que je n'ai pris en compte

2024-06-06 08:29 UTC, jsankare commented
Bah oui mais si la liste des changements n'est pas respectée alors ça veut dire que ça ne fonctionne pas bien, si on retire la navbar en entier ça va fonctionner mais ça sera pas bon par exemple. Et sur l'autre PR (https://github.com/jsankare/CMS-semestriel-1/pull/27) c'est impossible que ça fonctionne non plus.

2024-06-06 08:32 UTC, pierre265 commented
D'accord je fix tout ça

2024-06-10 16:50 UTC, jsankare requested changes
ça parait ok, juste est-ce que tu peux remettre le bouton de déconnection à droite et le relier correctement à la route de logout 
Il faudra aussi bien résoudre les conflits une fois que la PR sera validée, là pour le moment il y en a tu peux le voir le bot github le marque sur la pr

2024-06-10 21:07 UTC, jsankare requested changes

2024-06-11 07:26 UTC, jsankare approved these changes

2024-06-11 07:26 UTC, merged

2024-06-11 07:38 UTC, pierre265 commented on www/Public/scss/main.scss
Si