Feature/homepage
jsankare/CMS-semestriel-1 pull request #38
Opened 2024-06-13 15:58 UTC by pierre265

2024-06-17 14:08 UTC, jsankare requested changes

2024-06-17 14:08 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +    z-index: 1;
Necessaire de toucher au Z-index ?

2024-06-17 14:08 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +        background-color: grey;
$variable

2024-06-17 14:08 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +    font-family: inherit;
??

2024-06-17 14:08 UTC, jsankare commented on www/Views/Templates/front.php
>          <a href="#">Accueil</a>
tu peux mettre '/' ici pour rediriger a la racine si jamais

2024-06-17 14:08 UTC, jsankare commented on www/Views/Templates/front.php
> +            <button class="dropbtn">Pages
dropdown--button ferait pas plus sens (BEM) comme tu as fait en dessous avec le dropdown--content ?

2024-06-17 14:08 UTC, jsankare commented on www/Views/Templates/front.php
> +                <i class="fa fa-caret-down"></i>
interessante la classe du i, tu target ça ou juste tu as pas changé du copypasta ?

2024-06-17 14:08 UTC, jsankare commented on www/Views/Templates/front.php
> +        <div class="navbar-logo">
deux - pour le BEM

2024-06-21 14:49 UTC, jsankare requested changes
Review complété avec les screens & le message sur discord

2024-06-21 14:49 UTC, jsankare commented on www/Routes.yml
> +/page/{slug}/{id}:
Pourquoi tu fais en allant chercher le slug plus l'id alors que tu pourrais juste aller chercher par slug (c'et supposé être unique) ?

2024-06-21 14:49 UTC, jsankare commented on www/Routes.yml
> +  Security: True
True ici ? Pourquoi ?

2024-06-21 14:49 UTC, jsankare commented on www/dump.sql
> +    slug VARCHAR(255) UNIQUE NOT NULL,
Tu vois tu as bien mis le slug en unique alors no need pour l'id dans le path

2024-06-21 14:51 UTC, pierre265 commented on www/Routes.yml
> +/page/{slug}/{id}:
Oui, mais même là ça ne prendds pas en dynamique

2024-06-21 14:57 UTC, jsankare commented on www/Routes.yml
> +/page/{slug}/{id}:
Tu filer par le slug ou par l'id c'est la meme chose, juste si le slug a pas de match tu retourne une 404

2024-06-21 15:01 UTC, pierre265 commented on www/Routes.yml
> +/page/{slug}/{id}:
Oui, mais ça ne reconnais pas le {slug } dans la route

2024-06-21 16:02 UTC, jsankare commented on www/Routes.yml
> +/page/{slug}/{id}:
dans le show tu dois pouvoir le choper et t'en servie comme tu as fait avec le id, et de toute façon le show en page unique ne fonctionne pas du tout atm

2024-06-21 16:05 UTC, pierre265 commented on www/Routes.yml
> +/page/{slug}/{id}:
Je l'ai shopé dans le show, mais comment le renvoyer vers les routes

2024-06-25 16:53 UTC, closed without merging