Feature/slug
jsankare/CMS-semestriel-1 pull request #47
Opened 2024-06-28 10:06 UTC by pierre265

2024-06-28 13:35 UTC, jsankare requested changes
Voila pour mes retours, tu peux en profiter pour :
Passer les pages aux vues de connection & d'inscription

2024-06-28 13:35 UTC, jsankare commented on www/Models/Page.php
> +    public function findAllExcept(string $slug)
Bien ça

2024-06-28 13:35 UTC, jsankare commented on www/Models/Page.php
>      public function save(): void
A voir si tu peux pas utiliser la fonction save du Core/SQL plutot en ajoutant la condition pour le $isMain

2024-06-28 13:35 UTC, jsankare commented on www/Public/index.php
> +function mapSlugToRoute($uri, $routes) {
Tu peux pas mettre ça dans le fichier de config et l'importer ? On en avait deja parlé

2024-06-28 13:35 UTC, jsankare commented on www/Public/index.php
> +$listOfRoutes = [];
Pourquoi tu voudrais stocker & afficher toutes les routes ?

2024-06-28 13:35 UTC, jsankare commented on www/Public/index.php
> +if (!$requestedRoute || empty($listOfRoutes[$requestedRoute])) {
Je ne comprend pas pourquoi afficher toutes les routes c'est giga faille de sécurité

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +  background-color: $navColor;
Au final c'est plus géré ici tu peux virer

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +    color: white;
Pareil

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +  .logout {
pourquoi avoir 3 classes avec des noms différents qui font la meme chose ?

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +      background-color: grey;
variable sass color

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +    font-family: inherit;
Pas besoin

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +    background-color: grey;
Géré par la custom de la couleur de la nav aussi je pense

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +    min-width: 160px;
pas de px

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_frontNav.scss
> +        background-color: grey;
pareil

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_pageDisplayHome.scss
> +.page--wrappe {
toujours une typo ici

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_pageDisplayHome.scss
pourquoi je comprend pas il est front ou back lui ? mets dans les fichiers prévus à cet effet stp. Aussi, pourquoi la page home aurait un style différent que les autres sachant que la page home est une page comme les autres, la seule différence est que l'admin ou quoi décide de la mettre en avant

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_pageDisplayHome.scss
> +    font-size: 2em;
toujours des em au lieu des rem

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/components/_pageDisplayHome.scss
> +    padding-left: 0rem;
si tu mets 0 pas besoin de valeur

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/front.scss
> +@import "components/frontNav";
pas dans un dossier

2024-06-28 13:35 UTC, jsankare commented on www/Public/scss/front.scss
> +@import "components/pageDisplayHome";
pas dans un dossier

2024-06-28 13:35 UTC, jsankare commented on www/dump.sql
> +    content TEXT NOT NULL,
Pourquoi pas

2024-06-28 13:37 UTC, pierre265 commented on www/Views/Page/showpage.php
> +<div class="page--wrapper" >
Erreur

2024-06-28 13:38 UTC, pierre265 commented on www/Controllers/PageController.php
> +        $currentpage = (new Page())->findOneBySlug($slug);
Okay

2024-06-28 13:38 UTC, pierre265 commented on www/Controllers/PageController.php
> +            $view->assign('page', $mainPage);
Okay

2024-06-29 09:04 UTC, jsankare requested changes

2024-06-29 09:04 UTC, jsankare commented on www/Forms/PageForm.php
> +                    "required" => false,
je me repete mais si required = false pas besoin de le préciser

2024-06-29 09:04 UTC, jsankare commented on www/Forms/PageForm.php
> +                    "required" => false,
tu peux en profiter pour mettre la description de la page en true par contre pour le required

2024-06-29 09:04 UTC, jsankare commented on www/Public/scss/components/front/_frontNav.scss
> +      background-color: grey;
les variables couleur sass

2024-06-29 09:04 UTC, jsankare commented on www/Public/scss/components/front/_frontNav.scss
> +      background-color: grey;
les variables couleur sass

2024-06-29 09:04 UTC, jsankare commented on www/Public/scss/components/front/_frontNav.scss
> +    background-color: grey;
les variables couleur sass

2024-06-29 09:04 UTC, jsankare commented on www/Public/scss/components/front/_frontNav.scss
> +    min-width: 160px;
rem

2024-06-29 09:04 UTC, jsankare commented on www/Public/scss/components/front/_frontNav.scss
> +        background-color: grey;
les variables couleur sass

2024-06-29 09:04 UTC, jsankare commented on www/Public/scss/front.scss
> +@import "components/front/frontNav";
je chipote mais sur le principe si tu mets le fichier dans le dossier front tu as plus besoin de le préfixer de "front"

2024-06-29 09:04 UTC, jsankare commented on www/Views/Page/showpage.php
> +<div class="page--wrapper" >
pas changé

2024-06-29 10:12 UTC, pierre265 commented on www/Core/Form.php
> +                if ($input["type"] == "checkbox" && isset($input["checked"]) && $input["checked"]) {
C'est pour rendre là case is_main check quand on veut update une page

2024-06-29 10:16 UTC, pierre265 commented on www/Public/scss/components/front/_frontNav.scss
> +      background-color: grey;
Oui grey est une variable de couleur saas , ou bien ??

2024-06-29 10:45 UTC, jsankare requested changes

2024-06-29 10:45 UTC, jsankare commented on www/Forms/PageForm.php
> +                    "required" => false,
toujours un required false ici

2024-06-29 10:45 UTC, jsankare commented on www/Public/scss/components/front/_nav.scss
> +  // position: fixed;
si c'est commenté tu peux le virer

2024-06-29 10:45 UTC, jsankare commented on www/Public/scss/components/front/_nav.scss
>      float: right;
je t'avais dit pourquoi tu as 3 classes avec 3 noms differents qui font la meme chose ?

2024-06-29 10:45 UTC, jsankare commented on www/Public/scss/components/front/_nav.scss
> +      background-color: grey;
variable sass

2024-06-29 10:45 UTC, jsankare commented on www/Public/scss/components/front/_nav.scss
> +    color: white;
variable sass

2024-06-29 10:45 UTC, jsankare commented on www/Public/scss/components/front/_nav.scss
>      color: white;
variable sass

2024-06-29 10:45 UTC, jsankare commented on www/Public/scss/components/front/_nav.scss
>      color: white;
et en plus c'est géré par la feature des parametres donc inutile

2024-06-29 10:45 UTC, jsankare commented on www/Public/scss/components/front/_nav.scss
> +  // position: fixed;
et en plus c'est géré par la feature des parametres donc inutile (le navcolor ici)

2024-06-29 10:45 UTC, jsankare commented on www/Public/scss/components/front/_nav.scss
> +    background-color: grey;
variable sass

2024-06-29 10:45 UTC, jsankare commented on www/Public/scss/components/front/_nav.scss
> +        background-color: grey;
variable sass

2024-06-29 11:21 UTC, jsankare approved these changes

2024-06-29 11:21 UTC, jsankare commented on www/Public/scss/components/front/_nav.scss
> +  background-color: $navColor;
c'est plus géré ici ça encore une fois

2024-06-29 11:34 UTC, merged